import BoardRow from "./BoardRow.js";
import PromoteScreen from "./PromoteScreen.js";
import CheckmateScreen from "./CheckmateScreen.js";

export default function Board({
    pieces,
    setPieces,
    selectedPiece,
    setSelectedPiece,
    whiteToMove,
    setWhiteToMove,
    capturedPieces,
    setCapturedPieces,
    whiteKingSquare,
    setWhiteKingSquare,
    blackKingSquare,
    setBlackKingSquare,
    check,
    setCheck,
    checkmate,
    setCheckmate,
    promote,
    setPromote,
    moves,
    setMoves,
    analysisMode,
    setAnalysisMode,
    setAnalysisMoveNumber,
}) {
    return (
        <div className="board">
            <CheckmateScreen
                whiteToMove={whiteToMove}
                checkmate={checkmate}
                setWhiteToMove={setWhiteToMove}
                setCapturedPieces={setCapturedPieces}
                setWhiteKingSquare={setWhiteKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                setCheck={setCheck}
                setCheckmate={setCheckmate}
                setPromote={setPromote}
                setMoves={setMoves}
                setPieces={setPieces}
                setSelectedPiece={setSelectedPiece}
                analysisMode={analysisMode}
                setAnalysisMode={setAnalysisMode}
                setAnalysisMoveNumber={setAnalysisMoveNumber}
                moves={moves}
            />
            <PromoteScreen
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />

            <BoardRow
                row={8}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={7}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={6}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={5}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={4}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={3}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={2}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
            <BoardRow
                row={1}
                pieces={pieces}
                setPieces={setPieces}
                selectedPiece={selectedPiece}
                setSelectedPiece={setSelectedPiece}
                whiteToMove={whiteToMove}
                setWhiteToMove={setWhiteToMove}
                capturedPieces={capturedPieces}
                setCapturedPieces={setCapturedPieces}
                whiteKingSquare={whiteKingSquare}
                setWhiteKingSquare={setWhiteKingSquare}
                blackKingSquare={blackKingSquare}
                setBlackKingSquare={setBlackKingSquare}
                check={check}
                setCheck={setCheck}
                checkmate={checkmate}
                setCheckmate={setCheckmate}
                promote={promote}
                setPromote={setPromote}
                moves={moves}
                setMoves={setMoves}
                analysisMode={analysisMode}
            />
        </div>
    );
}
